Update dependencies and readme docs
P5-wrapper/react pull request #112
Opened 2021-09-06 16:50 UTC by jamesrweb

Updated dependencies and readme content to prepare for the next release.

2021-09-07 19:29 UTC, jamesrweb commented
@yevdyko remember to test the example in the docs on against the code in the branch, the NPM scripts, etc please 🙏

2021-09-07 22:14 UTC, yevdyko requested changes
@jamesrweb Thank you for updating the dependencies and README with the latest changes.

Looks good, but I noticed that another example has not been updated with the new component name.

The results of the library testing will be posted here tomorrow.

2021-09-07 22:14 UTC, yevdyko commented on README.md
>  import React from "react";
I wonder if the new `ReactP5Wrapper` component should also be used in the example below. See lines 72 and 90.

2021-09-07 22:14 UTC, yevdyko commented on package.json
> +    "release": "npm run build:demo && gh-pages -d dist && npm run build && npm publish",
🍬

2021-09-08 22:02 UTC, yevdyko reviewed
I tested the following things:

- NPM scripts work as expected, but the build script contains 3 warnings:

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  main.02992163650589778895.js (964 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (964 KiB)
      main.02992163650589778895.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

- `ReactP5Wrapper` component integrated in the React app. ✅ 
- Sketches in the demo work as expected. ✅ 
- Examples in the README can be improved by using more realistic sketches. See the comments.

2021-09-08 22:02 UTC, yevdyko commented on README.md
>    const sketch = p5 => {
What about a real sketch without using the `updateWithProps` prop?

For example:

```js
const sketch = p5 => {
  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.draw = () => {
    p5.background(250);
    p5.normalMaterial();
    p5.push();
    p5.rotateZ(p5.frameCount * 0.01);
    p5.rotateX(p5.frameCount * 0.01);
    p5.rotateY(p5.frameCount * 0.01);
    p5.plane(100);
    p5.pop();
  };
};

2021-09-08 22:02 UTC, yevdyko commented on README.md
>  import React from "react";
I don't think we need to import `React` here, as this could be confusing. We will do this where we render the `App` component.

2021-09-08 22:02 UTC, yevdyko commented on README.md
>  import React from "react";
This example is more realistic and uses rotation when rendering.

```js
import { Fragment, useState } from "react";
import { ReactP5Wrapper } from "react-p5-wrapper";

function App() {
  const sketch = p5 => {
    let rotation = 0;

    p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);
  
    p5.updateWithProps = props => {
      if (props.rotation) rotation = (props.rotation * Math.PI) / 180;
    };

    p5.draw = () => {
      p5.background(100);
      p5.normalMaterial();
      p5.noStroke();
      p5.push();
      p5.rotateY(rotation);
      p5.box(100);
      p5.pop();
    };
  };

  const [state, setState] = useState({ rotation: 160, sketch });

  return (
    <Fragment>
      <ReactP5Wrapper sketch={state.sketch} rotation={state.rotation} />
      <input
        type="range"
        defaultValue={state.rotation}
        min="0"
        max="360"
        step="1"
        onChange={event =>
          setState({ ...state, rotation: parseInt(event.target.value, 10) })
        }
      />
    </Fragment>
  );
}

export default App;
```

2021-09-08 22:02 UTC, yevdyko commented on package.json
>      "react-dom": "*"
`react` and `react-dom` must be at least `16.8.0`, as the component is based on React hooks.

I think this should also be mentioned in the README.

2021-09-09 13:10 UTC, jamesrweb commented on README.md
>  import React from "react";
As we are exposing a react component, we need to import react otherwise when it compiles it will be available only as a UMD global which we don't really want IMO.

2021-09-09 13:33 UTC, jamesrweb commented on README.md
>  import React from "react";
This is basically what w have within the `examples` folder and so I think we should keep the readme example a bit simpler, I added the version you previously suggested in the latest commit for that.

2021-09-09 13:33 UTC, jamesrweb commented on package.json
>      "react-dom": "*"
Good point, I updated the `peerDependencies` to reflect this.

2021-09-09 13:44 UTC, jamesrweb commented
> I tested the following things:
> 
> * NPM scripts work as expected, but the build script contains 3 warnings:
> 
> ```
> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets:
>   main.02992163650589778895.js (964 KiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (964 KiB)
>       main.02992163650589778895.js
> 
> WARNING in webpack performance recommendations:
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/
> ```
> 
> * `ReactP5Wrapper` component integrated in the React app. ✅
> * Sketches in the demo work as expected. ✅
> * Examples in the README can be improved by using more realistic sketches. See the comments.

In regards to the warnings, those are only for the demo and are due to webpack installing it's runtime into the output script. The production / release build uses rollup and doesn't have that issue and no warnings are thrown. Eventually it would be good to move the demo stuff over to rollup also to resolve that there too, WDYT? would you be interested in working on that as a followup for example? It would tidy the codebase a little further and would make for more performant demo builds and runtimes if we could get that working.

2021-09-09 13:45 UTC, jamesrweb commented
@yevdyko updated the docs and code, please check the wording and retest when you can 👍🏻

2021-09-09 17:44 UTC, yevdyko commented on README.md
>  import React from "react";
Makes sense.

2021-09-09 17:48 UTC, yevdyko commented
> > I tested the following things:
> > 
> > * NPM scripts work as expected, but the build script contains 3 warnings:
> > 
> > ```
> > WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> > This can impact web performance.
> > Assets:
> >   main.02992163650589778895.js (964 KiB)
> > 
> > WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> > Entrypoints:
> >   main (964 KiB)
> >       main.02992163650589778895.js
> > 
> > WARNING in webpack performance recommendations:
> > You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> > For more info visit https://webpack.js.org/guides/code-splitting/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * `ReactP5Wrapper` component integrated in the React app. ✅
> > * Sketches in the demo work as expected. ✅
> > * Examples in the README can be improved by using more realistic sketches. See the comments.
> 
> In regards to the warnings, those are only for the demo and are due to webpack installing it's runtime into the output script. The production / release build uses rollup and doesn't have that issue and no warnings are thrown. Eventually it would be good to move the demo stuff over to rollup also to resolve that there too, WDYT? would you be interested in working on that as a followup for example? It would tidy the codebase a little further and would make for more performant demo builds and runtimes if we could get that working.

Perhaps, I can improve this during the current month. Let's create an issue for that.

2021-09-09 17:49 UTC, yevdyko approved these changes
It looks good! The examples work as expected after your changes.

Thanks @jamesrweb 🚀

2021-09-09 17:49 UTC, merged